# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca24d3d3d1aa90b1b12b4b8b191dac989b7e2865277e3c0eb4cbdb96bc0979b14ea9d38f9e6cc66fa8131a68475009a3240b34c012aa43118f0020bc7b16441

test:
  secret_key_base: eb434d76f2e1ee086def5e2a5c8b9bf63ff910076b569a36fd98b63e6bc07572dc920c8fe3332892f6d8eca3cded422bd29c93b1c6b3d14bad2cd53a76c344b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
